
on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v2
      - name: Install nix.
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install tlacli.
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            tlacli
      - name: Install happy.
        run: |
          cabal update
          cabal install happy
      - name: Install jq.
        run: |
          sudo apt-get install jq
      - name: chmod the test script.
        run: |
          chmod u+x tests/integration/run-tests.sh
      - name: Building and testing of pirtla.
        run: |
          nix-shell --run "./tests/integration/run-tests.sh --ci" --allowed-uris 'https://github.com/NixOS/nixpkgs https://github.com/input-output-hk https://github.com/NixOS/nixpkgs-channels' --option trusted-public-keys "hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" --option substituters "https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/"

